# Coverage boundary (~ outer boundary should be simple and counter-clockwise oriented)
# coverage_boundary: [[80., 80.], [-80., 80.], [-80., -80.], [80., -80.]]

# Room with obstacles outer boundary
# coverage_boundary: [[-100., 90.], [-100., -70.], [-20., -70.], [-20., 90.]]

# Room with all obstacles integrated, but one
# coverage_boundary: [[-100., 90.], [-100., 70.], [-70., 70.], [-70., 64.], 
#                     [-100., 64.], [-100., 26.], [-72., 26.], [-72., 38.], 
#                     [-66., 38.], [-66., 22.], [-100., 22.], [-100., -70.], 
#                     [-80., -70.], [-80., -22.], [-74., -22.], [-74., -48.], 
#                     [-54., -48.], [-54., -54.], [-74., -54.], [-74., -70.], 
#                     [-20., -70.], [-20., 10.], [-60., 10.], [-60., 14.], 
#                     [-20., 14.], [-20., 52.], [-50., 52.], [-50., 56.], 
#                     [-20., 56.], [-20., 90.], [-56., 90.], [-56., 74.], 
#                     [-60., 74.], [-60., 90.]]

# Six (6) shape with hole
# coverage_boundary: [[-80., 130.], [-80., 10.], [20., 10.], [20., 80.], 
#                     [-70., 80.], [-70., 120.], [20., 120.], [20., 130.]]

# Ugly environment
# coverage_boundary: [[80., 140.], [120., 100.], [80., 100.], [20., 140.], 
#                     [40., 60.], [-40., 40.], [80., -20.], [80., 80.], 
#                     [160., -20.], [140., 80.], [300., 20.], [300., 120.], 
#                     [260., 60.], [180., 80.], [160., 180.], [320., 160.], 
#                     [140., 220.], [140., 120.]]

# coverage_boundary: [[20., 140.], [20., 80.], [40., 80.], [20., 60.], 
#                     [20., -40.], [30., -40.], [30., 60.], [40., 60.], 
#                     [40., -30.], [50., -30.], [50., 60.], [60., 60.], 
#                     [60., -20.], [70., -20.], [70., 60.], [90., 60.], 
#                     [90., -20.], [100., -20.], [100., 60.], [110., 60.], 
#                     [110., -30.], [120., -30.], [120., 60.], [130., 60.], 
#                     [130., -40.], [140., -40.], [140., 60.], [120., 80.], 
#                     [140., 80.], [140., 140.]]

# Letter A
# coverage_boundary: [[65., 65.], [40., 15.], [50., 15.], [60., 35.], 
#                     [70., 35.], [80., 15.], [90., 15.]]

# spiral
# coverage_boundary: [[120., 140.], [50., 140.], [50., 90.], [115., 90.], 
#                     [115., 130.], [60., 130.], [60., 100.], [105., 100.], 
#                     [105., 120.], [70., 120.], [70., 115.], [100., 115.],
#                     [100., 105.], [65., 105.], [65., 125.], [110., 125.],
#                     [110., 95.], [55., 95.], [55., 135.], [120., 135.]]

# corridors
# coverage_boundary: [[-140., 120.], [-200., 120.], [-200., -20.], [-120., -20.], 
#                     [-120., -100.], [20., -100.], [20., -20.], [100., -20.], 
#                     [100., 100.], [20., 100.], [20., 160.], [-140., 160.]]

# Weird E letter
coverage_boundary: [[-90., 120.], [-90., 10.], [-10., 10.], [-10., 20.], 
                    [-80., 20.], [-80., 40.], [-10., 40.], [-10., 60.], 
                    [-80., 50.], [-80., 70.], [-30., 60.], [-20., 80.], 
                    [-80., 80.], [-80., 90.], [-10., 90.], [-10., 100.], 
                    [-80., 100.], [-80., 110.], [-10., 110.], [-10., 120.]]

# Coverage obstacles should be simple and clockwie oriented
coverage_obstacles:
    obs: [[-2220., -2190.], [-2190., -2220.], [-2210., -2230.], [-2240., -2190.]]
    #################
    # obs1: [[65., 50.], [70., 40.], [60., 40.]]
    #################
    # Square env with large obs
    # obs: [[60., -60.], [-60., -60.], [-60., 60.], [60., 60.]]
    #################
    # Six
    # obs: [[-70., 70.], [10., 70.], [10., 20.], [-70., 20.]]
    #################
    # obs1: [[-20., 10.], [10., -20.], [-10., -30.], [-40., 10.]]
    # obs2: [[-20., 40.], [0., 30.], [0., 20.], [-40., 30.]]
    # obs3: [[-40., -10.], [-30., -30.], [-50., -20.], [-50., -10.]]
    #################
    # obs1: [[-60., 60.], [-20., 60.], [-20., 20.], [-60., 20.]]
    # obs2: [[20., 60.], [60., 60.], [60., 20.], [20., 20.]]
    # obs3: [[20., -20.], [60., -20.], [60., -60.], [20., -60.]]
    # obs4: [[-60., -20.], [-20., -20.], [-20., -60.], [-60., -60.]]
    # obs5: [[-10., 10.], [10., 10.], [10., -10.], [-10., -10.]]
    #################
    # obs1: [[-20., 50.], [-20., 40.], [20., 40.], [20., 50.]]
    # obs2: [[60., 40.], [40., 40.], [40., 20.], [60., 20.]]
    # obs3: [[60., -40.], [40., -40.], [40., -60.], [70., -60.]]
    # obs4: [[20., -70.], [20., -60.], [-20., -60.], [-20., -73.]]
    # obs5: [[-68., -60.], [-40., -60.], [-40., -20.], [0., -20.], [0., 20.], [-68., 20.]]
    #################
    # obs1: [[50., 90.], [40., 60.], [10., 60.], [20., 90.]]
    # obs2: [[10., 10.], [30., 10.], [30., -30.], [10., -30.]]
    # obs3: [[-70., 20.], [-40., 10.], [-70., -30.]]
    # obs4: [[-20., 90.], [-20., 40.], [-50., 70.]]
    #################
    # Room with obstacles
    # obs1: [[-60., 87.], [-56., 87.], [-56., 74.], [-60., 74.]]
    # obs2: [[-97., 70.], [-70., 70.], [-70., 64.], [-97., 64.]]
    # obs3: [[-50., 56.], [-22., 56.], [-22., 53.], [-50., 53.]]
    # obs4: [[-98., 26.], [-72., 26.], [-72., 37.], [-66., 37.], [-66., 23.], [-98., 23.]]
    # obs5: [[-60., 14.], [-24., 14.], [-24., 9.], [-60., 9.]]
    # obs6: [[-52., -14.], [-28., -14.], [-28., -30.], [-32., -30.], [-32., -17.], [-52., -17.]]
    # obs7: [[-80., -22.], [-74., -22.], [-74., -48.], [-54., -48.], 
    #        [-54., -54.], [-74., -54.], [-74., -68.], [-80., -68.]]
    #################
    # Room with all obstacles integrated, but one
    # obs1: [[-52., -14.], [-28., -14.], [-28., -30.], [-32., -30.], [-32., -17.], [-52., -17.]]
    #################
    # Call of Ktulhu
    # obs1: [[30., 130.], [70., 130.], [70., 100.], [30., 100.]]
    # obs2: [[90., 130.], [130., 130.], [130., 100.], [90., 100.]]
    # obs3: [[50., 80.], [60., 90.], [100., 90.], [110., 80.], 
    #        [90., 85.], [80., 70.], [70., 85.]]
    #################
    # Corridors obstacles
    # obs1: [[-180., 100.], [-140., 100.], [-140., 0.], [-180., 0.]]
    # obs2: [[-120., 140.], [0., 140.], [0., 100.], [-120., 100.]]
    # obs3: [[20., 80.], [80., 80.], [80., 0.], [20., 0.]]
    # obs4: [[-100., -40.], [0., -40.], [0., -80.], [-100., -80.]]
    # obs5: [[-120., 80.], [0., 80.], [0., 60.], [-40., 60.], [-40., 20.], [0., 20.], 
    #         [0., -20.], [-100., -20.], [-100., 20.], [-60., 20.], [-60., 60.], [-120., 60.]]
    #################

motion_params:
    delta_t: 2.
    attraction_const: 1.
    repulsion_const: 10.
    vmax: 1.
    umax: 2.
    wmax: 0.5236 # pi / 6.
    # wmax: 1.5708 # pi / 2.
    physical_radius: 0.5
    safe_radius: 2.
    K_linear: 1.
    K_angular: 1.
    K_repulsion: 0.
    K_attraction: 1.
    K_goal: 5.

sensing_params:
    sense_fp_phys_rad_scale: 4.
    sigma_local: 2.
    sense_radius: 7.
    hfov_range_deg: 180.

behaviours:
    stationary: false
    limited_sensing: false
    flocking: false
    planning: true
    visibility: true
    voronoi: true

# centroid_alg: "frontier_focused"
# centroid_alg: "geodesic_approximate"
# centroid_alg: "geometric"
# centroid_alg: "grid_based"
centroid_alg: "continuous_dijkstra"

centroidal_mtr: "radius_min_sum"
# centroidal_mtr: "radius_min_max"
# centroidal_mtr: "closeness"
# centroidal_mtr: "betweenness"
# centroidal_mtr: "k_avg_radius"

k_avg_count: 3

agent_init_rand_seed: 897435

debug:
    exec_time_log: true