# coverage_boundary: [[-80., 60.], [-20., 60.], [-20., 40.], [20., 40.], 
#                     [20., 60.], [80., 60.], [80., 40.], [40., 40.], 
#                     [40., 20.], [80., 20.], [80., -40.], [40., -40.], 
#                     [40., -60.], [80., -60.], [80., -80.], [20., -80.], 
#                     [20., -60.], [-20., -60.], [-20., -80.], [-80., -80.], 
#                     [-80., -60.], [-40., -60.], [-40., -20.], [0., -20.], 
#                     [0., 20.], [-80., 20.]]

# coverage_boundary: [[80., 100.], [50., 90.], [40., 60.], [10., 60.], 
#                     [20., 90.], [-20., 90.], [-50., 70.], [-20., 40.], 
#                     [-40., 10.], [-80., 10.], [-80., -40.], [10., -30.], 
#                     [10., 10.], [30., 10.], [30., -30.], [80., -40.], [70., 20.]]

# coverage_boundary: [[80., 100.], [80., -40.], [-80., -40.], [-80., 100.]]

# Coverage boundary (~ outer boundary should be simple and counter-clockwise oriented)
coverage_boundary: [[80., 80.], [-80., 80.], [-80., -80.], [80., -80.]]

# Coverage obstacles should be simple and clockwie oriented
coverage_obstacles:
    # obs: [[-220., -190.], [-190., -220.], [-210., -230.], [-240., -190.]]
    #################
    # obs: [[-8., 67.], [8., 67.], [8., 8.], [64., 8.], 
    #       [64., -8.], [8., -8.], [8., -68.], [-8., -68.], 
    #       [-8., -8.], [-68., -8.], [-68., 8.], [-8., 8.]]
    #################
    # obs1: [[-20., 10.], [10., -20.], [-10., -30.], [-40., 10.]]
    # obs2: [[-20., 40.], [0., 30.], [0., 20.], [-40., 30.]]
    # obs3: [[-40., -10.], [-30., -30.], [-50., -20.], [-50., -10.]]
    #################
    obs1: [[-60., 60.], [-20., 60.], [-20., 20.], [-60., 20.]]
    obs2: [[20., 60.], [60., 60.], [60., 20.], [20., 20.]]
    obs3: [[20., -20.], [60., -20.], [60., -60.], [20., -60.]]
    obs4: [[-60., -20.], [-20., -20.], [-20., -60.], [-60., -60.]]
    obs5: [[-10., 10.], [10., 10.], [10., -10.], [-10., -10.]]
    #################
    # obs1: [[-20., 50.], [-20., 40.], [20., 40.], [20., 50.]]
    # obs2: [[60., 40.], [40., 40.], [40., 20.], [60., 20.]]
    # obs3: [[60., -40.], [40., -40.], [40., -60.], [70., -60.]]
    # obs4: [[20., -70.], [20., -60.], [-20., -60.], [-20., -73.]]
    # obs5: [[-68., -60.], [-40., -60.], [-40., -20.], [0., -20.], [0., 20.], [-68., 20.]]
    #################
    # obs1: [[50., 90.], [40., 60.], [10., 60.], [20., 90.]]
    # obs2: [[10., 10.], [30., 10.], [30., -30.], [10., -30.]]
    # obs3: [[-70., 20.], [-40., 10.], [-70., -30.]]
    # obs4: [[-20., 90.], [-20., 40.], [-50., 70.]]

motion_params:
    delta_t: 0.2
    attraction_const: 0.8
    repulsion_const: 0.8
    vmax: 1.
    umax: 1.
    wmax: 0.5236 # pi / 6.
    # wmax: 1.5708 # pi / 2.
    physical_radius: 0.5
    safe_radius: 2.
    K_linear: 1.
    K_angular: 1.
    K_repulsion: 0.
    K_attraction: 0.
    K_goal: 0.2

sensing_params:
    sigma_local: 2.
    sense_radius: 7.
    hfov_range_deg: 180.

behaviours:
    stationary: false
    limited_sensing: false
    flocking: false
    planning: true
    visibility: true
    voronoi: true

centroid_alg: "frontier_focused"
# centroid_alg: "geodesic_approximate"
# centroid_alg: "geometric"

debug:
    exec_time_log: true