# Coverage boundary (~ outer boundary should be simple and counter-clockwise oriented)
# coverage_boundary: [[160., 160.], [-160., 160.], [-160., -160.], [160., -160.]]
# coverage_name: "square_cvx"

# Corridors
coverage_boundary: [[-180., 240.], [-180., 20.], [-20., 20.], [-20., 40.], 
                    [-160., 40.], [-160., 60.], [-20., 60.], [-20., 100.], 
                    [-160., 100.], [-160., 140.], [-60., 120.], [-40., 160.], 
                    [-160., 160.], [-160., 180.], [-20., 180.], [-20., 200.], 
                    [-160., 200.], [-160., 220.], [-20., 220.], [-20., 240.]]
coverage_name: "corridors"

# CorridorsLarge
# coverage_boundary: [[-240., 240.], [-240., 20.], [-20., 20.], [-20., 40.], 
#                     [-160., 40.], [-160., 60.], [-20., 60.], [-20., 100.], 
#                     [-160., 100.], [-160., 140.], [-60., 120.], [-40., 160.], 
#                     [-160., 160.], [-160., 180.], [-20., 180.], [-20., 200.], 
#                     [-160., 200.], [-160., 220.], [-20., 220.], [-20., 240.]]
# coverage_name: "corridorsLarge"

# coverage_boundary: [[0., 10.], [55., 10.], [55., 80.], [65., 80.],
#                     [65., 10.], [110., 10.], [110., 80.], [120., 80.],
#                     [120., 10.], [165., 10.], [165., 80.], [175., 80.],
#                     [175., 10.], [225., 10.], [225., 140.], [160., 140.],
#                     [160., 115.], [150., 115.], [150., 180.], [160., 180.],
#                     [160., 150.], [225., 150.], [225., 240.], [160., 240.],
#                     [160., 210.], [150., 210.], [150., 240.], [75., 240.],
#                     [75., 210.], [65., 210.], [65., 240.], [0., 240.]]
# coverage_name: "ROMER"

# coverage_boundary: [[-160., 260.], [-160., 20.], [40., 20.], [40., 160.], 
#                     [-140., 160.], [-140., 240.], [40., 240.], [40., 260.]]
# coverage_name: "six_with_hole"

# Coverage obstacles should be simple and clockwie oriented
coverage_obstacles:
    obs: []
    #################
    # obs: [[-2220., -2190.], [-2190., -2220.], [-2210., -2230.], [-2240., -2190.]]
    #################
    # ROMER
    # obs1: [[85., 180.], [125., 180.], [125., 155.], [105., 155.],
    #        [105., 135.], [125., 135.], [125., 115.], [85., 115.]]
    # obs2: [[20., 180.], [60., 180.], [60., 115.], [20., 115.]]
    #################
    # Six
    # obs: [[-140., 140.], [20., 140.], [20., 40.], [-140., 40.]]

motion_params:
    # delta_t: 2.
    delta_t: 1.
    attraction_const: 1.
    repulsion_const: 10.
    vmax: 1.
    umax: 2.
    wmax: 0.5236 # pi / 6.
    # wmax: 1.5708 # pi / 2.
    physical_radius: 1.
    safe_radius: 2.
    K_linear: 1.
    K_angular: 1.
    K_repulsion: 5.
    K_attraction: 1.
    K_goal: 1.
    communication_tolerance: 120.

sensing_params:
    sense_fp_phys_rad_scale: 5.
    sigma_local: 2.
    sense_radius: 80.
    hfov_range_deg: 180.
    boundary_tolerance: 2.

behaviours:
    stationary: false
    limited_sensing: false
    flocking: false
    planning: true
    visibility: false
    voronoi: true

centroid_alg: "geodesic_approximate"
# centroid_alg: "geometric"
# centroid_alg: "continuous_dijkstra"

centroidal_mtr: "radius_min_sum"
# centroidal_mtr: "radius_min_max"
# centroidal_mtr: "closeness"
# centroidal_mtr: "betweenness"
# centroidal_mtr: "k_avg_radius"

k_avg_count: 3

continuous_iteration_threshold: 500
discrete_iteration_threshold: 500

plotting_title: "Standard Distributed Lloyd"

agent_init_rand_seed: 409

comm_range: 322
comm_range_test: false

random_kill: false
random_kill_per: 10

debug:
    exec_time_log: true
